kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: nginx
  name: nginx-exporter-stress
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '* * * * *'
  startingDeadlineSeconds: 5
  concurrencyPolicy: Allow
  historyLimit: 1
  type: StressChaos
  stressChaos:
    selector:
      namespaces:
        - nginx
      labelSelectors:
        'pod_type': 'exporter'
    mode: all
    containerNames: ['nginx-exporter']
    stressors:
      memory:
        workers: 1
        size: 20%
      cpu:
        workers: 2
        load: 20
    duration: 20s
