commonLabels:
  object: nginx

nodeSelector:
    node-role: worker

serverBlock: |-
  vhost_traffic_status_zone;
  server {
    listen 8080;
    include  "/opt/bitnami/nginx/conf/bitnami/*.conf";

    location /vts_status {
      vhost_traffic_status_display;
      vhost_traffic_status_display_format html;
    }

    location /stub_status {
      stub_status on;
      access_log   off;
    }
  }

service:
  type: NodePort

resources:
  limits:
    cpu: 200m
    memory: 200Mi