commonLabels:
  object: nginx

nodeSelector:
    node-role: worker

serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location /stub_status {
      stub_status on;
      access_log   off;
    }
  }

service:
  type: NodePort

resources:
  limits:
    cpu: 200m
    memory: 200Mi