commonLabels:
  object: nginx

nodeSelector:
    node-role: worker

serverBlock: |-
  upstream backend{
    server 127.0.0.1:80;
  }

  vhost_traffic_status_zone;
  vhost_traffic_status_filter_by_host on;
  vhost_traffic_status_filter_by_set_key $status $server_name;

  server {
    server_name *.weops.org;

    listen 8080;
    include  "/opt/bitnami/nginx/conf/bitnami/*.conf";

    location /vts_status {
      vhost_traffic_status_display;
      vhost_traffic_status_display_format html;
    }

    location /stub_status {
      stub_status on;
      access_log   off;
    }
  }

service:
  type: NodePort

resources:
  limits:
    cpu: 200m
    memory: 200Mi