apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
      - name: ffmpeg
        image: jrottenberg/ffmpeg:3-scratch
        args: ["-hide_banner",
               "-re", "-f", "lavfi", "-i", "testsrc2=size=1280x720:rate=30", "-pix_fmt", "yuv420p",
               "-c:v", "libx264", "-x264opts", "keyint=30:min-keyint=30:scenecut=-1",
               "-tune", "zerolatency", "-profile:v", "high", "-preset", "veryfast", "-bf", "0", "-refs", "3",
               "-b:v", "1400k", "-bufsize", "1400k",
               "-utc_timing_url", "https://time.akamai.com/?iso", "-use_timeline", "0", "-media_seg_name", "chunk-stream-$RepresentationID$-$Number%05d$.m4s",
               "-init_seg_name", "init-stream1-$RepresentationID$.m4s",
               "-window_size", "5", "-extra_window_size", "10", "-remove_at_exit", "1", "-adaptation_sets", "id=0,streams=v id=1,streams=a",
               "-f", "flv", "rtmp://nginx-rtmp-service.nginx:1935/stream/hello"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg-service
  namespace: nginx
spec:
  selector:
    app: ffmpeg
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935