apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: alfg/nginx-rtmp:v1.6.0
        ports:
        - name: stream
          containerPort: 1935
        - name: server
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
  namespace: nginx
spec:
  selector:
    app: nginx-rtmp
  ports:
    - name: stream
      protocol: TCP
      port: 1935
      targetPort: 1935
      nodePort: 30101
    - name: server
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
  type: NodePort
